{{- if .Values.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "edd-platform.fullname" . }}-migrations
  labels:
    {{- include "edd-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  {{- if .Values.migrations.useHelmHooks }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    helm.sh/hook-weight: "-5"
  {{- end }}
spec:
  backoffLimit: {{ .Values.migrations.backoffLimit }}
  template:
    metadata:
      labels:
        {{- include "edd-platform.baseSelectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "edd-platform.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - alembic
            - upgrade
            - head
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "edd-platform.fullname" . }}-config
            - secretRef:
                name: {{ include "edd-platform.secretName" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
{{- end }}
