{{- if .Values.worker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edd-platform.workerName" . }}
  labels:
    {{- include "edd-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "edd-platform.workerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "edd-platform.workerSelectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "edd-platform.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.worker.command | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            - name: APP_PROCESS_ROLE
              value: "worker"
          envFrom:
            - configMapRef:
                name: {{ include "edd-platform.fullname" . }}-config
            - secretRef:
                name: {{ include "edd-platform.secretName" . }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
{{- end }}
